const data =
    [
        {
            "id": "1",
            "name": "Куртка 'QWETRY'",
            "img": "./img/item__1.svg",
            "description": "Осенняя куртка из сентипона, дёшево и беспонтово!",
            "price": "25.00",
            "color": "blue",
            "size": "L",
            "quantity": "1",
        },
        {
            "id": "2",
            "name": "Костюм 'IVIVI'",
            "img": "./img/item__2.svg",
            "description": "Хз что за костюм, не разбераюсь в женской одежде",
            "price": "58.00",
            "color": "black",
            "size": "S",
            "quantity": "1",
        },
        {
            "id": "3",
            "name": "Худи 'TOY'",
            "img": "./img/item__3.svg",
            "description": "Худи на любителя.",
            "price": "44.50",
            "color": "blue; black",
            "size": "L",
            "quantity": "1",
        },
        {
            "id": "4",
            "name": "Брюки 'CAPSULE'",
            "img": "./img/item__4.svg",
            "description": "Жёлтые, модные брюки - живи ярко!",
            "price": "35.00",
            "color": "yellow",
            "size": "L",
            "quantity": "1",
        },
        {
            "id": "5",
            "name": "Пиджак 'BLUE JACKET'",
            "img": "./img/item__5.svg",
            "description": "Пиджак голубой, больше добавить нечего.",
            "price": "77.30",
            "color": "cyan",
            "size": "M",
            "quantity": "1",
        },
        {
            "id": "6",
            "name": "Полосатая рубашка 'PRISON'",
            "img": "./img/item__6.svg",
            "description": "Небо в клеточку, друзья в полосочку.",
            "price": "105.00",
            "color": "marsh",
            "size": "XS",
            "quantity": "1",
        },
    ];
const productDataJson = JSON.stringify(data);